# Generated by Django 5.2.4 on 2025-07-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('senha', models.CharField(max_length=100)),
                ('funcao', models.CharField(choices=[('admin', 'Administrador'), ('comum', 'Comum')], default='comum', max_length=20)),
            ],
        ),
    ]
